#!/bin/bash
source /opt/ros/humble/setup.bash
source ~/vrx_ws/install/setup.bash

# List all topics
ros2 topic list
# Get the information for a specific topic; useful to get the underlying type
ros2 topic info ...
# Log all publications on a topic
ros2 topic echo ...